### ISSUE TITLE
Design Methodology

### ISSUE THREAD

**Issue by ishita-kumar** [airavata-courses/ScrumLords#92]
Hi Team, 
I see that your project makes use of many technologies that my project lacks. Just out of curiosity, what was your thought approach in selecting these design paradigms. ( PubSub, Redis)
For example, I realize google cloud is much more in demand in the industry than OpenStack, so would this be a reason for doing so? 
Also, what is the reason behind using nginx instead of the google cloud load balancer?

**Comment by VishalUzumaki** [comment]
I am facing the same issue I am new to Reddis and Helm so if you can give a summary how it fits in the cloud architecture.

**Comment by bobbyrathoree** [comment]
Right, so Redis: it's a highly available caching database that we deployed on our Kubernetes cluster to prevent our PubSub (message broker) from endlessly retrying on failed messages. And Helm: think of brew for Mac and apt for Ubuntu. It is essentially a package manager for Kubernetes. We install charts using helm that are made by fellow developers all over the world, for convenience. I hope that addresses your query.

**Comment by bobbyrathoree** [comment]
@ishita-kumar To address your concerns, we used PubSub cause it made more sense to use in-house products that Google provides in their cloud platform, for better integration purposes. Built on top of RabbitMQ, it is blazing fast and handles our use cases pretty well. 

Additionally, I wanted to explore and build a project from the ground up, to production in GCP, which is why we went for it instead of the open sourced OpenStack. 

The reason we used the nginx load balancer instead of Google's is because it provides certain features that better fitted to our use cases. Https load balancers aren't natively supported in GCE LB, so we went with nginx. You can read more about it [here](https://cloud.google.com/community/tutorials/https-load-balancing-nginx).
